name = "mozule-site"
main = "src/worker.js"
compatibility_date = "2024-01-01"
workers_dev = false

[[routes]]
pattern = "mozule.co.jp/*"
zone_name = "mozule.co.jp"

[[send_email]]
name = "CONTACT_EMAIL"
destination_address = "masaki.takatori@mozule.co.jp"

[assets]
directory = "./dist"
binding = "ASSETS"
